// L4: upgrading a PRIOR RELEASED SCHEMA, not just migrating an empty database
// (E02-B10, 000-docs/044 §3; 041 §10's "apply clean to an empty DB AND to the
// previous snapshot").
//
// `migrations.test.ts` proves the easy half. This proves the half that breaks in
// production: a database that already holds an older schema AND older rows, taken
// to head. Two things it asserts that nothing else could:
//
//   1. **The E02-D05 downgrade hazard.** `003`'s trigger loop is DROP-then-CREATE
//      and `CREATE TRIGGER` always lands at the bypassable `tgenabled='O'` default.
//      Any upgrade path that re-runs a pre-`006` migration silently downgrades the
//      sole enforcement of locked decision 4. So after every upgrade this test
//      asserts the whole declared trigger set is back at `'A'`.
//   2. **The grant step survives new tables.** `CREATE TABLE` grants privileges to
//      nobody, so every migration that adds a table leaves the app role unable to
//      read it until the grants are re-derived. Three tables arrive between `003`
//      and head; the assertion is that the run ends with a grant line naming them.
//
// The fixtures are generated by `pnpm fixture:schema` and checked in. They carry a
// `schema_migrations` table with NO `checksum` column, which is the shape every
// real database has today — so this is also the only place the runner's
// `adopt-checksum` path is exercised.
import { readFileSync } from "node:fs";
import { afterAll, describe, expect, it } from "vitest";
import pg from "pg";
import { appUrl, createFreshDb, probeDb, restoreFixture, runMigrations } from "./helpers.js";
import { APPEND_ONLY_TABLES } from "../../src/db/appendOnlyTables.js";
import { checkAppendOnlyTriggers } from "../../src/services/appendOnlyDetector.js";
import { readMigrations } from "../../scripts/migrationDiscipline.js";

const dbUp = await probeDb();

/** Every released snapshot we keep a fixture for, and how many migrations it holds. */
const SNAPSHOTS = [
  { name: "003", file: "tests/fixtures/schema/after-003.sql", applied: 3 },
  { name: "006", file: "tests/fixtures/schema/after-006.sql", applied: 6 },
  // E02-D07: added because 011/012 pushed HEAD four past `006` and the assertion
  // at the foot of this file is the reminder E02-B10 left for exactly this
  // moment — "when a future bead ships 011, add the 010 fixture rather than keep
  // testing an ever-older upgrade". An upgrade test whose starting point drifts
  // ever further from the shape anyone actually deploys stops testing an upgrade
  // and starts testing archaeology.
  { name: "010", file: "tests/fixtures/schema/after-010.sql", applied: 10 },
] as const;

const HEAD_COUNT = readMigrations().length;

describe.skipIf(!dbUp)("upgrading a prior released schema", () => {
  const pools: pg.Pool[] = [];
  afterAll(async () => {
    await Promise.all(pools.map((p) => p.end()));
  });

  for (const snap of SNAPSHOTS) {
    describe(`from the schema at ${snap.name}`, () => {
      it("restores, upgrades to head, and leaves every append-only trigger ENABLE ALWAYS", async () => {
        const url = await createFreshDb(`longbox_upgrade_${snap.name}`);
        await restoreFixture(url, snap.file);

        const pool = new pg.Pool({ connectionString: url });
        pools.push(pool);

        // The fixture is genuinely the OLD shape: no checksum column, and the
        // tables a later migration adds are absent.
        const preLedger = await pool.query(`SELECT count(*)::int AS n FROM schema_migrations`);
        expect((preLedger.rows[0] as { n: number }).n).toBe(snap.applied);
        const preCols = await pool.query(
          `SELECT 1 FROM information_schema.columns
            WHERE table_name = 'schema_migrations' AND column_name = 'checksum'`
        );
        expect(preCols.rowCount).toBe(0);

        const out = await runMigrations(url);

        // Every already-applied file adopts its checksum ONCE, loudly, and nothing
        // re-applies it — the path every real database takes exactly once.
        for (const f of readMigrations().slice(0, snap.applied)) {
          expect(out).toContain(`skip  ${f.filename}  (adopted checksum`);
        }
        for (const f of readMigrations().slice(snap.applied)) {
          expect(out).toContain(`apply ${f.filename}`);
        }
        expect(out).toContain("migrations up to date");
        // The grant step ran and covered the tables that did not exist in the fixture.
        expect(out).toMatch(/grants {2}longbox_app: \d+ append-only/);

        // (1) THE DOWNGRADE HAZARD. Nothing on the upgrade path may leave a trigger
        // at the bypassable 'O' default.
        const triggers = await checkAppendOnlyTriggers(pool);
        expect(triggers).toEqual({ ok: true, missing: [], disabled: [], undeclared: [] });

        const ledger = await pool.query(
          `SELECT count(*)::int AS n, count(checksum)::int AS c FROM schema_migrations`
        );
        expect(ledger.rows[0]).toEqual({ n: HEAD_COUNT, c: HEAD_COUNT });

        // (2) THE GRANT STEP, proved from the APP role rather than from the log
        // line: the least-privileged connection can read a table that did not exist
        // in the fixture, and still cannot update an append-only one.
        const app = new pg.Pool({ connectionString: appUrl(url) });
        pools.push(app);
        await expect(app.query(`SELECT count(*) FROM scan_session_transition`)).resolves.toBeDefined();
        // …and is refused an UPDATE at the PRIVILEGE layer, before the trigger even
        // fires: E02-D06 grants an append-only table `SELECT, INSERT` and nothing
        // more, so the upgrade path is proved to leave both controls in place, not
        // just the trigger.
        await expect(app.query(`UPDATE human_confirmation SET source = 'x'`)).rejects.toThrow(
          /permission denied for table human_confirmation/
        );

        // A second run is a clean skip: no adoption, no re-apply, no drift.
        const second = await runMigrations(url);
        expect(second).not.toContain("adopted checksum");
        expect(second).not.toContain("apply ");
      }, 120_000);

      it("derives authored_by for the rows that were already there, per 041 §10.1", async () => {
        const pool = pools[0];
        expect(pool).toBeDefined();
        const url = await createFreshDb(`longbox_authored_${snap.name}`);
        await restoreFixture(url, snap.file);
        await runMigrations(url);
        const p = new pg.Pool({ connectionString: url });
        pools.push(p);

        // The one COLUMN-derivation: `candidate_set.method` decides, and the fixture
        // seeds one row on each side of it.
        const cs = await p.query(`SELECT method, authored_by FROM candidate_set ORDER BY method`);
        expect(cs.rows).toEqual([
          { method: "barcode", authored_by: "system" },
          { method: "llm_vision", authored_by: "provider" },
        ]);

        // The path-derivations, on rows written before the column existed.
        const rest = await p.query(
          `SELECT (SELECT authored_by FROM scan_photo LIMIT 1)           AS photo,
                  (SELECT authored_by FROM human_confirmation LIMIT 1)   AS confirmation,
                  (SELECT authored_by FROM condition_assessment LIMIT 1) AS condition,
                  (SELECT authored_by FROM cost_log LIMIT 1)             AS cost`
        );
        expect(rest.rows[0]).toEqual({
          photo: "human",
          confirmation: "human",
          condition: "human",
          cost: "system",
        });

        // 041 §5.3: session_seq is NEVER backfilled. A reconstructed sequence would
        // be a fabricated observation about what order things happened in.
        const seq = await p.query(
          `SELECT count(*)::int AS n FROM human_confirmation WHERE session_seq IS NOT NULL`
        );
        expect((seq.rows[0] as { n: number }).n).toBe(0);
      }, 120_000);
    });
  }

  // A fixture that has silently stopped matching the migration that produced it is
  // worse than no fixture: it makes the upgrade test pass against a shape nobody
  // ships. The generated header is the marker that it came from the generator.
  it("keeps both fixtures machine-generated, not hand-edited", () => {
    for (const snap of SNAPSHOTS) {
      const text = readFileSync(snap.file, "utf8");
      expect(text.startsWith("-- GENERATED FIXTURE — do not hand-edit.")).toBe(true);
      expect(text).toContain(`--   pnpm fixture:schema --upto ${snap.name}`);
    }
  });

  it("covers the newest released schema, so the fixture set cannot silently go stale", () => {
    // The newest fixture must stay within four migrations of head. E02-B10 wrote
    // this assertion with `006` as the newest and said in so many words that
    // shipping `011` was the moment to add `010`; E02-D07 shipped `011`/`012` and
    // added it. The next bead to push head past `014` adds the next one.
    const newest = SNAPSHOTS[SNAPSHOTS.length - 1]!;
    expect(HEAD_COUNT - newest.applied).toBeLessThanOrEqual(4);
    const trigger = APPEND_ONLY_TABLES.find((t) => t.table === "scan_session_transition");
    expect(trigger?.since).toBe("010_scan_session_transition.sql");
    // And the outbox's own tables are declared against the migration that
    // created them, which is what makes the `011` half of this upgrade real
    // rather than assumed.
    for (const table of ["outbox", "outbox_attempt"]) {
      expect(APPEND_ONLY_TABLES.find((t) => t.table === table)?.since).toBe("011_outbox.sql");
    }
  });
});
