// L4: upgrading a PRIOR RELEASED SCHEMA, not just migrating an empty database
// (E02-B10, 000-docs/044 §3; 041 §10's "apply clean to an empty DB AND to the
// previous snapshot").
//
// `migrations.test.ts` proves the easy half. This proves the half that breaks in
// production: a database that already holds an older schema AND older rows, taken
// to head. Two things it asserts that nothing else could:
//
//   1. **The E02-D05 downgrade hazard.** `003`'s trigger loop is DROP-then-CREATE
//      and `CREATE TRIGGER` always lands at the bypassable `tgenabled='O'` default.
//      Any upgrade path that re-runs a pre-`006` migration silently downgrades the
//      sole enforcement of locked decision 4. So after every upgrade this test
//      asserts the whole declared trigger set is back at `'A'`.
//   2. **The grant step survives new tables.** `CREATE TABLE` grants privileges to
//      nobody, so every migration that adds a table leaves the app role unable to
//      read it until the grants are re-derived. Three tables arrive between `003`
//      and head; the assertion is that the run ends with a grant line naming them.
//
// The fixtures are generated by `pnpm fixture:schema` and checked in. They carry a
// `schema_migrations` table with NO `checksum` column, which is the shape every
// real database has today — so this is also the only place the runner's
// `adopt-checksum` path is exercised.
import { readFileSync } from "node:fs";
import { afterAll, describe, expect, it } from "vitest";
import pg from "pg";
import { appUrl, createFreshDb, probeDb, restoreFixture, runMigrations } from "./helpers.js";
import { checkTenantIsolation, describeTenantIsolationFailure } from "../../src/services/roleSeparation.js";
import { APPEND_ONLY_TABLES } from "../../src/db/appendOnlyTables.js";
import { checkAppendOnlyTriggers } from "../../src/services/appendOnlyDetector.js";
import { readMigrations } from "../../scripts/migrationDiscipline.js";

const dbUp = await probeDb();

/** Every released snapshot we keep a fixture for, and how many migrations it holds. */
const SNAPSHOTS = [
  { name: "003", file: "tests/fixtures/schema/after-003.sql", applied: 3 },
  { name: "006", file: "tests/fixtures/schema/after-006.sql", applied: 6 },
  // E02-D07: added because 011/012 pushed HEAD four past `006` and the assertion
  // at the foot of this file is the reminder E02-B10 left for exactly this
  // moment — "when a future bead ships 011, add the 010 fixture rather than keep
  // testing an ever-older upgrade". An upgrade test whose starting point drifts
  // ever further from the shape anyone actually deploys stops testing an upgrade
  // and starts testing archaeology.
  { name: "010", file: "tests/fixtures/schema/after-010.sql", applied: 10 },
  // E06-D01: added because `015` pushed head five past `010`, which is one more
  // than the assertion at the foot of this file allows — the same reminder that
  // E02-B10 left and E02-D07 answered, firing on schedule. `014` rather than
  // `015` deliberately: a snapshot is a schema someone could be RUNNING, and
  // `015` is the one that PR was adding. The newest RELEASED schema was `014`.
  //
  // E04-D01 KEEPS THIS ROW AND ADDS NONE. This bead's `016`/`017` put head five
  // past `010` too, and it had staged an `after-013` for exactly that reason —
  // but `014` is both NEWER and the shape production actually runs, and head 017
  // is three past it, inside the limit. Two fixtures three migrations apart would
  // be two upgrade paths tested to prove one property, so `after-013` was dropped
  // rather than kept for symmetry.
  { name: "014", file: "tests/fixtures/schema/after-014.sql", applied: 14 },
  // E03-D09: added because `019`/`020` pushed head SIX past `014`, two more
  // than the assertion at the foot of this file allows — the third time that
  // reminder has fired on schedule (E02-B10 wrote it; E02-D07 and E06-D01
  // answered it before). `018` rather than `020`, for E06-D01's reason exactly:
  // a snapshot is a schema somebody could be RUNNING, and `019`/`020` are the
  // ones this PR is adding. `018` is E03-B07's, merged ahead of this branch, so
  // it is also the newest RELEASED schema at the moment this fixture was cut.
  //
  // It is also the first fixture whose upgrade exercises a DATA statement:
  // `019` creates one `organization` per existing `shop` and populates the FK in
  // the same transaction (034 §4.3, A4), so this suite is where "a shop row that
  // existed before the migration comes out the other side with a legal party" is
  // PROVED rather than asserted — on a fixture whose `shop` row predates the
  // column entirely.
  { name: "018", file: "tests/fixtures/schema/after-018.sql", applied: 18 },
  // E03-B05: added because `021`–`023` pushed head FIVE past `018`, one more
  // than the assertion at the foot of this file allows — the fourth time that
  // reminder has fired on schedule. `020` rather than `023`, for the same reason
  // every row above gives: a snapshot is a schema somebody could be RUNNING, and
  // `021`–`023` are the ones this PR is adding. `020` is E03-D09's, merged ahead
  // of this branch.
  //
  // ⚠ CUTTING IT REQUIRED A CHANGE TO THE GENERATOR, and the change is a finding
  // rather than a convenience. `FIXTURE_SEED` inserted a `shop` row naming no
  // organization, which `019`'s validated `shop_has_a_legal_party` CHECK refuses
  // — so the seed could not be applied to any database migrated past `018` and
  // no fixture at or beyond `019` was cuttable at all. The seed is now
  // snapshot-aware at the two points a constraint forced it to be (the
  // organization, and `023`'s `spend_owner`), by probing the catalog rather than
  // by forking per snapshot. Nothing else about it moved, and the fixed uuids are
  // unchanged, so an older fixture regenerated today still diffs as a schema
  // change rather than as noise.
  { name: "020", file: "tests/fixtures/schema/after-020.sql", applied: 20 },
  // E03-D07 shipped `024` and added this one. With `020` alone the newest
  // fixture would sit exactly four behind head, which passes today and fails on
  // the next migration anybody writes — and the point of the assertion at the
  // foot of this file is that the set does not go stale silently. `023` is the
  // last schema released before this bead's own migration, so it is the one an
  // operator upgrading a deployed database would actually be starting from.
  { name: "023", file: "tests/fixtures/schema/after-023.sql", applied: 23 },
  // E03-B03 shipped `028` and added this one, **before the assertion at the foot
  // of this file forced it**. With `023` alone the newest fixture sits three
  // behind a head of 26 — inside the limit — so nothing was red. It is added
  // anyway because of the gap: E03-B06 is landing `026` and `027` on this same
  // base, and the moment it merges head becomes 28, which is FIVE past `023` and
  // fails for whichever branch merges second. That failure would arrive as a
  // stranger's red build on somebody else's PR. `025` rather than `028`, for the
  // reason every row above gives: a snapshot is a schema somebody could be
  // RUNNING, and `028` is the one this PR is adding.
  { name: "025", file: "tests/fixtures/schema/after-025.sql", applied: 25 },
  // E03-B04 shipped `029` and added this one. `028` is the last schema RELEASED
  // before this bead's migration, so it is what an operator upgrading a deployed
  // database starts from — and it is the snapshot that proves the interesting
  // half of `029`: a database that already has rows gets row-level security and a
  // policy on every shop-scoped table, applied by the runner's re-derived plan
  // (`src/db/rowLevelSecurity.ts`) rather than by the migration file alone.
  //
  // E02-D11's `030` upgrades from the SAME fixture and adds no new one: head is
  // then 29 files, two past this row's 27, inside the limit the foot of this file
  // asserts. It uses the row for a second property — that `030`'s columns arrive
  // EMPTY on a row that predates them (041 §10.1's no-fabricated-observation
  // rule) — which is why the `authored_by` case below now reads them too.
  //
  // `applied: 27` and not 28: the ledger counts FILES, and `027` was reserved by
  // E03-B06 and never written, so the twenty-seven files up to and including
  // `028` are what a database at that schema has applied.
  { name: "028", file: "tests/fixtures/schema/after-028.sql", applied: 27 },
  // ONE row, added independently by TWO beads for two different reasons, kept as
  // one because the row is the same row: same snapshot, same file, same applied
  // count, and a second copy would only run the fixture twice.
  //
  // E03-D14 added it **before the assertion at the foot of this file forced
  // it** — for E03-B03's reason exactly, one bead later. With `028` alone the
  // newest fixture sat three behind a head of 30, inside the limit, so nothing
  // was red that day; it was added anyway because of the gap, since the moment
  // `031` merged head became 31 — FOUR past `028`, the limit itself, so the very
  // next migration anybody wrote would have failed on a stranger's PR.
  //
  // E03-D11 needs the same snapshot for a stronger reason: `030` is the last
  // schema RELEASED before `031`, so it is what an operator upgrading a deployed
  // database starts from — and it is the snapshot that proves the interesting
  // half of `031`, which is the half a fresh database cannot show: **three
  // `NOT NULL`s are DROPPED and a CHECK is WIDENED on a table that already holds
  // rows.**
  //
  // ⚠ **AND THE ROWS HAD TO BE PUT THERE, which the first version of this comment
  // claimed without arranging** (the invariant review's WARN 2). `FIXTURE_SEED`
  // seeded no `app_session` at all, so the validation this row calls the
  // "interesting half" ran over ZERO rows and proved only that the DDL parses.
  // The seed now has a third snapshot-aware branch carrying one device session
  // and one operator session on top of it, and the standalone case near the foot
  // of this file asserts they are there BEFORE it upgrades — because a case that
  // silently found none would go on passing for exactly the wrong reason. The two
  // `ENABLE ALWAYS` triggers this bead adds are covered by the same case's
  // trigger assertion below.
  //
  // `030` rather than `032`, for the reason every row above gives: a snapshot is
  // a schema somebody could be RUNNING, never one a PR is adding.
  //
  // `applied: 29` and not 30: the ledger counts FILES, and `027` was reserved by
  // E03-B06 and never written, so the twenty-nine files up to and including
  // `030` are what a database at that schema has applied.
  { name: "030", file: "tests/fixtures/schema/after-030.sql", applied: 29 },
  // E03-D19 shipped `034` and added this one. `033` is the newest RELEASED schema
  // at the moment this fixture was cut, and it is the one that matters most for
  // this particular migration: `034` does not add a column, it adds a CONSTRAINT
  // and then VALIDATEs it, and a validation is only interesting against a
  // database that already holds rows. The fixture's seed hangs a `scan_photo`, two
  // `candidate_set` rows, a `human_confirmation`, a `condition_assessment` and a
  // `cost_log` off one session — six rows across five of the ten children — so the
  // upgrade path proves the composite foreign keys validate on existing data
  // rather than only on an empty table.
  //
  // `applied: 32` and not 33: the ledger counts FILES, and `027` is absent —
  // reserved by E03-B06 and never written. `031` IS present: E03-D11 merged
  // ahead of this branch, and the fixture was RE-CUT afterwards for exactly that
  // reason, because `031` sorts before `033` and a fixture cut without it would
  // have described a schema nobody ships while `readMigrations().slice(0, 32)`
  // said otherwise. Thirty-two files up to and including `033` are what a
  // database at that schema has applied.
  { name: "033", file: "tests/fixtures/schema/after-033.sql", applied: 32 },
  // E03-D21 shipped `036` and added this one. ⚠ **AND THE ARITHMETIC IS NOT WHY**
  // — 36 files against `033`'s 32 is 4, which is exactly the limit and not past
  // it, so the assertion at the foot of this file would have stayed green with no
  // new fixture. Two things made it owed anyway. First, the prose of the last two
  // beads promised it twice ("the next bead to push head past `034` adds the next
  // one"), and a promise a suite keeps deferring is a rule nobody is following.
  // Second, `036` is the FIRST migration whose whole content is a tenant
  // BOUNDARY: a policy plus a function plus a privilege class, none of which the
  // other snapshots exercise. Restoring a schema that predates it and migrating
  // INTO it is the only test that proves an operator upgrading a running database
  // ends up behind the boundary rather than merely that a fresh one starts there.
  //
  // `applied: 34` and not 35: the ledger counts FILES, and `027` is absent —
  // reserved by E03-B06 and never written. Thirty-four files up to and including
  // `035` are what a database at that schema has applied.
  { name: "035", file: "tests/fixtures/schema/after-035.sql", applied: 34 },
] as const;

const HEAD_COUNT = readMigrations().length;

describe.skipIf(!dbUp)("upgrading a prior released schema", () => {
  const pools: pg.Pool[] = [];
  afterAll(async () => {
    await Promise.all(pools.map((p) => p.end()));
  });

  for (const snap of SNAPSHOTS) {
    describe(`from the schema at ${snap.name}`, () => {
      it("restores, upgrades to head, and leaves every append-only trigger ENABLE ALWAYS", async () => {
        const url = await createFreshDb(`longbox_upgrade_${snap.name}`);
        await restoreFixture(url, snap.file);

        const pool = new pg.Pool({ connectionString: url });
        pools.push(pool);

        // The fixture is genuinely the OLD shape: no checksum column, and the
        // tables a later migration adds are absent.
        const preLedger = await pool.query(`SELECT count(*)::int AS n FROM schema_migrations`);
        expect((preLedger.rows[0] as { n: number }).n).toBe(snap.applied);
        const preCols = await pool.query(
          `SELECT 1 FROM information_schema.columns
            WHERE table_name = 'schema_migrations' AND column_name = 'checksum'`
        );
        expect(preCols.rowCount).toBe(0);

        const out = await runMigrations(url);

        // Every already-applied file adopts its checksum ONCE, loudly, and nothing
        // re-applies it — the path every real database takes exactly once.
        for (const f of readMigrations().slice(0, snap.applied)) {
          expect(out).toContain(`skip  ${f.filename}  (adopted checksum`);
        }
        for (const f of readMigrations().slice(snap.applied)) {
          expect(out).toContain(`apply ${f.filename}`);
        }
        expect(out).toContain("migrations up to date");
        // The grant step ran and covered the tables that did not exist in the fixture.
        expect(out).toMatch(/grants {2}longbox_app: \d+ append-only/);

        // (1) THE DOWNGRADE HAZARD. Nothing on the upgrade path may leave a trigger
        // at the bypassable 'O' default.
        const triggers = await checkAppendOnlyTriggers(pool);
        expect(triggers).toEqual({ ok: true, missing: [], disabled: [], undeclared: [] });

        const ledger = await pool.query(
          `SELECT count(*)::int AS n, count(checksum)::int AS c FROM schema_migrations`
        );
        expect(ledger.rows[0]).toEqual({ n: HEAD_COUNT, c: HEAD_COUNT });

        // (2) THE GRANT STEP, proved from the APP role rather than from the log
        // line: the least-privileged connection can read a table that did not exist
        // in the fixture, and still cannot update an append-only one.
        const app = new pg.Pool({ connectionString: appUrl(url) });
        pools.push(app);
        await expect(app.query(`SELECT count(*) FROM scan_session_transition`)).resolves.toBeDefined();
        // …and is refused an UPDATE at the PRIVILEGE layer, before the trigger even
        // fires: E02-D06 grants an append-only table `SELECT, INSERT` and nothing
        // more, so the upgrade path is proved to leave both controls in place, not
        // just the trigger.
        await expect(app.query(`UPDATE human_confirmation SET source = 'x'`)).rejects.toThrow(
          /permission denied for table human_confirmation/
        );

        // (2b) THE TENANT BOUNDARY, on a database that predates it (E03-B04).
        // This is the half `migrations/029` alone would not prove: the policies are
        // re-derived and re-applied by the RUNNER after every migration run
        // (`src/db/rowLevelSecurity.ts`), so a deployed database gets them on the
        // upgrade — and this asserts it from the APP role, which is the role they
        // bind. `checkTenantIsolation` is the same function the server calls at
        // boot before it binds a port.
        const isolation = await checkTenantIsolation(app);
        expect(describeTenantIsolationFailure(isolation)).toBe("");
        expect(isolation.ok).toBe(true);
        // And the boundary is REAL on the upgraded database, not merely declared:
        // the fixture's own seeded rows are invisible without a context.
        await expect(app.query(`SELECT id FROM scan_session`)).resolves.toMatchObject({ rows: [] });

        // (2c) `034`'s COMPOSITE TENANT KEYS, VALIDATED ON ROWS THAT WERE ALREADY
        // THERE (E03-D19). This is the half an empty database cannot prove: `034`
        // adds no column, it adds ten foreign keys and then runs
        // `VALIDATE CONSTRAINT` over the child tables, and a validation is only
        // interesting against rows written before the constraint existed. The
        // fixture seeds a `scan_photo`, two `candidate_set` rows, a
        // `human_confirmation`, a `condition_assessment` and a `cost_log` off one
        // session, so five of the ten children carry real rows on this path.
        //
        // `convalidated` is the assertion and not merely `conname`: a constraint
        // left NOT VALID refuses new rows and vouches for none of the existing
        // ones, which is a weaker guarantee wearing the same name.
        const anchors = await pool.query(
          `SELECT c.relname::text AS child, k.convalidated AS validated
             FROM pg_constraint k
             JOIN pg_class c ON c.oid = k.conrelid
             JOIN pg_class cf ON cf.oid = k.confrelid
            WHERE k.contype = 'f' AND cf.relname = 'scan_session'
            ORDER BY 1`
        );
        expect(anchors.rows).toHaveLength(10);
        expect(anchors.rows.every((r) => (r as { validated: boolean }).validated)).toBe(true);
        // And the single-column edge it supersedes is gone, on the upgrade path as
        // much as on a fresh database.
        const singles = await pool.query(
          `SELECT count(*)::int AS n
             FROM pg_constraint k
             JOIN pg_class cf ON cf.oid = k.confrelid
            WHERE k.contype = 'f' AND cf.relname = 'scan_session'
              AND array_length(k.conkey, 1) = 1`
        );
        expect((singles.rows[0] as { n: number }).n).toBe(0);

        // A second run is a clean skip: no adoption, no re-apply, no drift.
        const second = await runMigrations(url);
        expect(second).not.toContain("adopted checksum");
        expect(second).not.toContain("apply ");
      }, 120_000);

      it("derives authored_by for the rows that were already there, per 041 §10.1", async () => {
        const pool = pools[0];
        expect(pool).toBeDefined();
        const url = await createFreshDb(`longbox_authored_${snap.name}`);
        await restoreFixture(url, snap.file);
        await runMigrations(url);
        const p = new pg.Pool({ connectionString: url });
        pools.push(p);

        // The one COLUMN-derivation: `candidate_set.method` decides, and the fixture
        // seeds one row on each side of it.
        const cs = await p.query(`SELECT method, authored_by FROM candidate_set ORDER BY method`);
        expect(cs.rows).toEqual([
          { method: "barcode", authored_by: "system" },
          { method: "llm_vision", authored_by: "provider" },
        ]);

        // The path-derivations, on rows written before the column existed.
        const rest = await p.query(
          `SELECT (SELECT authored_by FROM scan_photo LIMIT 1)           AS photo,
                  (SELECT authored_by FROM human_confirmation LIMIT 1)   AS confirmation,
                  (SELECT authored_by FROM condition_assessment LIMIT 1) AS condition,
                  (SELECT authored_by FROM cost_log LIMIT 1)             AS cost`
        );
        expect(rest.rows[0]).toEqual({
          photo: "human",
          confirmation: "human",
          condition: "human",
          cost: "system",
        });

        // 041 §5.3: session_seq is NEVER backfilled. A reconstructed sequence would
        // be a fabricated observation about what order things happened in.
        const seq = await p.query(
          `SELECT count(*)::int AS n FROM human_confirmation WHERE session_seq IS NOT NULL`
        );
        expect((seq.rows[0] as { n: number }).n).toBe(0);

        // E02-D11 / 029: and the causal reference is not backfilled either, for a
        // stronger version of the same reason — nobody recorded what was on the
        // screen, so a value invented on the upgrade path would be a fabricated
        // observation about what a PERSON was looking at, in the one column that
        // exists to answer that question. The columns arrive; they arrive empty.
        const against = await p.query(
          `SELECT count(*)::int AS rows,
                  count(against_table)::int AS named
             FROM human_confirmation`
        );
        expect(against.rows[0]).toEqual({ rows: 1, named: 0 });
      }, 120_000);
    });
  }

  // A fixture that has silently stopped matching the migration that produced it is
  // worse than no fixture: it makes the upgrade test pass against a shape nobody
  // ships. The generated header is the marker that it came from the generator.
  it("keeps both fixtures machine-generated, not hand-edited", () => {
    for (const snap of SNAPSHOTS) {
      const text = readFileSync(snap.file, "utf8");
      expect(text.startsWith("-- GENERATED FIXTURE — do not hand-edit.")).toBe(true);
      expect(text).toContain(`--   pnpm fixture:schema --upto ${snap.name}`);
    }
  });

  // 019's PRECONDITION, proved by making it fire (E03-D09; raised by the advisory
  // review on PR #71). The migration adds `operator_id`'s foreign key on four
  // tables and asserts, in a comment, that nothing has ever written the column.
  // The `ALTER TABLE` would fail on its own if that were false — but it would
  // fail with a bare foreign-key violation naming a constraint that did not
  // exist a moment earlier, on a run at 7am. The explicit check says what the
  // rows ARE and what the operator has to decide.
  it("REFUSES to add the operator_id foreign key over a row naming an unknown operator", async () => {
    const url = await createFreshDb("longbox_upgrade_orphan_operator");
    await restoreFixture(url, "tests/fixtures/schema/after-018.sql");
    const pool = new pg.Pool({ connectionString: url });
    pools.push(pool);

    // A row from a world this migration cannot account for: `operator_id` set to
    // a uuid no `app_user` will ever have, because `app_user` does not exist yet
    // in the fixture.
    await pool.query(
      `UPDATE scan_session SET operator_id = '99999999-9999-4999-8999-999999999999'
        WHERE id = '22222222-2222-4222-8222-222222222221'`
    );

    await expect(runMigrations(url)).rejects.toThrow(
      /refusing to add the operator_id foreign key: 1 row\(s\) in scan_session/
    );

    // And it refused BEFORE altering anything: the constraint is absent, so a
    // second run after the operator has decided what the row is starts clean.
    const constraint = await pool.query(
      `SELECT 1 FROM pg_constraint WHERE conname = 'scan_session_operator_is_an_app_user'`
    );
    expect(constraint.rowCount).toBe(0);
  });

  // E03-D11's `031` is the first migration in this tree to WIDEN a CHECK on a
  // table that already holds rows, and a CHECK added by `ALTER TABLE` is
  // VALIDATED against every one of them. Over an empty table that validation is
  // vacuous — which is exactly what this suite was doing until `FIXTURE_SEED`
  // grew its third snapshot-aware branch (the invariant review's WARN 2).
  it("validates 031's tightened shape CHECK against sessions that were ALREADY THERE", async () => {
    const url = await createFreshDb("longbox_upgrade_live_sessions");
    await restoreFixture(url, "tests/fixtures/schema/after-030.sql");
    const pool = new pg.Pool({ connectionString: url });
    pools.push(pool);

    // The premise, asserted rather than assumed: the snapshot really does carry
    // one session of each device-bound kind. Without this the case below would
    // pass just as well over zero rows, which is the failure it exists to close.
    const before = await pool.query(`SELECT kind FROM app_session ORDER BY kind`);
    expect(before.rows).toEqual([{ kind: "device" }, { kind: "operator" }]);

    await runMigrations(url);

    // `031` DROPS three `NOT NULL`s and re-adds the shape CHECK with the device
    // and operator disjuncts asserting those same three columns explicitly —
    // because they were implied by the `NOT NULL`s a moment earlier and are not
    // any more. If either disjunct were wrong, THIS is where it would have
    // failed: the ALTER would have aborted on a pre-existing row.
    const after = await pool.query(
      `SELECT kind, device_id IS NOT NULL AS has_device, location_id IS NOT NULL AS has_location
         FROM app_session ORDER BY kind`
    );
    expect(after.rows).toEqual([
      { kind: "device", has_device: true, has_location: true },
      { kind: "operator", has_device: true, has_location: true },
    ]);

    // …and the widened CHECK still REFUSES the shapes it was tightened to refuse:
    // a device session with no device is now representable by the column types
    // and must not be representable by the constraint.
    await expect(
      pool.query(
        `INSERT INTO app_session
           (chain_id, kind, shop_id, location_id, device_id, device_credential_id,
            token_hash, rotate_after, idle_expires_at, absolute_expires_at)
         SELECT gen_random_uuid(), 'device', shop_id, location_id, NULL, NULL,
                'fixture-not-a-real-token-000000000003',
                now() + interval '1 day', now() + interval '1 day', now() + interval '1 day'
           FROM app_session WHERE kind = 'device'`
      )
    ).rejects.toThrow(/app_session_kind_shape/);
  });

  it("covers the newest released schema, so the fixture set cannot silently go stale", () => {
    // The newest fixture must stay within four migrations of head. E02-B10 wrote
    // this assertion with `006` as the newest and said in so many words that
    // shipping `011` was the moment to add `010`; E02-D07 shipped `011`/`012` and
    // added it; E06-D01 shipped `015`, which put head five past `010`, and added
    // `014`; E03-D09 shipped `019`/`020` and added `018`; E03-B05 shipped
    // `021`–`023` and added `020`; E03-D07 shipped `024` and added `023` rather than
    // leave the set exactly at the limit; E03-B04 shipped `029` and added `028`;
    // E02-D11 shipped `030` and added NONE, because `028` still sits two behind
    // head; E03-D14 shipped `032` and added `030`, again rather than leave the
    // set one migration from the limit while E03-D11's `031` was in flight; and
    // E03-D19 shipped `034` and added `033` — not because the limit forced it
    // either, but because `034`'s whole content is a constraint VALIDATED over
    // existing rows, and the snapshot immediately before it is the only fixture
    // that tests that on the shape an operator actually upgrades from; and
    // E03-D21 shipped `036` and added `035` — this time not because the limit
    // forced it either (36 against 32 is exactly 4), but because `036` is the
    // first migration that is ENTIRELY a tenant boundary, and the only way to
    // show that an operator's RUNNING database ends up behind it is to restore
    // one that predates it and migrate in.
    // E03-B08 shipped `038` and added NONE, and the reason is stated because the
    // default in this file has lately been to add one anyway. Two things decide
    // it. **The limit does not force it** — head is a COUNT and not a number
    // (`027` is the only gap, and `037` closed the one it briefly held when
    // E03-D24 merged ahead of this branch), so at 37 files `035`'s 34 still sits
    // three behind and inside the four. **And `035` is already the
    // right snapshot for what `038` does**: its only reach into an existing table
    // is `ADD COLUMN … NOT NULL DEFAULT 'accepted'` on
    // `connector_webhook_receipt`, whose truth claim is about ROWS THAT ARE
    // ALREADY THERE — every receipt written before this migration WAS accepted —
    // and a fixture predating `026` would have no such rows to prove it on, while
    // `035` has the table and the shape an operator actually upgrades from. A
    // fixture cut at `036` would test the same statement against the same shape
    // one migration later.
    const newest = SNAPSHOTS[SNAPSHOTS.length - 1]!;
    expect(HEAD_COUNT - newest.applied).toBeLessThanOrEqual(4);
    const trigger = APPEND_ONLY_TABLES.find((t) => t.table === "scan_session_transition");
    expect(trigger?.since).toBe("010_scan_session_transition.sql");
    // And the outbox's own tables are declared against the migration that
    // created them, which is what makes the `011` half of this upgrade real
    // rather than assumed.
    for (const table of ["outbox", "outbox_attempt"]) {
      expect(APPEND_ONLY_TABLES.find((t) => t.table === table)?.since).toBe("011_outbox.sql");
    }
  });
});
