# ENGINEER-OWNED TEMPLATE (generated by implement-tests 2026-09-01).
# Refine the wording/scenarios to match how the shop actually talks about the
# flow, then hash-pin via `pnpm exec audit-harness init`. No BDD runner is
# wired yet — these scenarios currently trace to tests/integration/smoke.http.test.ts
# and the unit suites (see tests/RTM.md); wire cucumber-js later if Wall-1 glue
# is wanted.

Feature: Scan a comic and land a draft listing
  A shop employee photographs a back-issue, confirms what it is, calls the
  condition in plain retail language, and a DRAFT listing lands in Shopify.
  Nothing publishes without a human (locked decision).

  Background:
    Given a registered shop with a pricing policy of 90% of comps, a $3.00 floor, and nearest-99 rounding

  Scenario: Happy path from scan to Shopify draft
    Given an in-progress scan session
    When the employee confirms "Amazing Spider-Man #300" from the candidate grid
    And records the condition as "FN to VF" with defects "spine ticks, corner wear"
    And requests a price for "amazing spider-man 300"
    And requests a Shopify draft
    Then the session status is "drafted"
    And the Shopify product is created with status "DRAFT"
    And the session's event trail shows the confirmation, condition, pricing snapshot, and draft

  Scenario: Evidence contradiction forces human review
    Given the model ranks a candidate as issue "300" with high confidence
    But its own evidence says it read issue number "#301" on the cover
    Then the confidence band is downgraded from "high" to "medium"
    And the employee must pick from the candidate grid instead of one-tap confirming

  Scenario: No pricing policy blocks pricing
    Given a shop that has not run register-shop
    When the employee requests a price
    Then the request is rejected with a conflict explaining the missing policy

  Scenario: A draft needs a confirmed identification first
    Given an in-progress scan session with no human confirmation
    When the employee requests a Shopify draft
    Then the request is rejected with a conflict explaining the missing confirmation
